# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  - name: solution
    value: '**/*.sln'
  - name: buildPlatform
    value: 'Any CPU'
  - name: buildConfiguration
    value: 'Release'
  #- group: KeyVaultVariables
  #- name: 'AuthClientID'
  #  value: $(AuthClientID)
  #- name: 'AuthClientSecret'
  #  value: $(AuthClientSecret)

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

#- task: CmdLine@2
#  inputs:
#    script: |
#      echo AuthClientID
#      echo AuthClientSecret

#- task: AzureKeyVault@2
#  inputs:
#    azureSubscription: 'Azure for Students (b3d5f944-8fc9-497b-b3cf-2c0c442a68f6)'
#    KeyVaultName: 'ThamcoSecretVault'
#    SecretsFilter: '*'
#    RunAsPreJob: false

#- task: FileTransform@1
#  inputs:
#    folderPath: '$(System.DefaultWorkingDirectory)/**/'
#    fileType: 'json'
#    targetFiles: 'CustomerAccountDeletionRequest/appsettings.json'

#- task: replacetokens@4
#  inputs:
#    rootDirectory: '$(System.DefaultWorkingDirectory)/**/'
#    targetFiles: '
#    encoding: 'auto'
#    tokenPattern: 'doublebraces'
#    writeBOM: true
#    actionOnMissing: 'warn'
#    keepToken: false
#    actionOnNoFiles: 'continue'
#    enableTransforms: false
#    useLegacyPattern: false
#    enableTelemetry: true

- task: replacetokens@4
  inputs:
    rootDirectory: '$(System.DefaultWorkingDirectory)/**/'
    targetFiles: 'CustomerAccountDeletionRequest/appsettings.json'
    encoding: 'auto'
    tokenPattern: 'doublebraces'
    writeBOM: true
    actionOnMissing: 'fail'
    keepToken: false
    actionOnNoFiles: 'fail'
    enableTransforms: false
    useLegacyPattern: false
    enableTelemetry: true'

#- task: PowerShell@2
#  inputs:
#    targetType: 'inline'
#   script: |
#     $pathToJson = "SamLearnsAzure/SamLearnsAzure.Tests/appsettings.json"
#         $a = Get-Content $pathToJson | ConvertFrom-Json
#         $a.AppSettings.ClientSecret = ${{parameters.clientSecret}}
#         $a.AppSettings.RedisConnection =  ${{parameters.redisConnection}} 
#         $a | ConvertTo-Json | set-content $pathToJson

- task: DotNetCoreCLI@2
  displayName: 'Run unit tests - $(buildConfiguration)'
  inputs:
    command: 'test'
    arguments: '--no-build --configuration $(buildConfiguration)'
    publishTestResults: true
    projects: '**/CustomerAccountDeletionRequestTests/*.csproj'

- task: DotNetCoreCLI@2
  displayName: 'Run integration tests - $(buildConfiguration)'
  inputs:
    command: 'test'
    arguments: '--no-build --configuration $(buildConfiguration)'
    publishTestResults: true
    projects: '**/DeletionRequestIntegrationTests/*.csproj'

- task: PublishBuildArtifacts@1