// <auto-generated />
using System;
using CustomerAccountDeletionRequest.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CustomerAccountDeletionRequest.Migrations
{
    [DbContext(typeof(Context.Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CustomerAccountDeletionRequest.DomainModels.DeletionRequestModel", b =>
                {
                    b.Property<int>("DeletionRequestID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CustomerID")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateApproved")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateRequested")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletionReason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DeletionRequestStatus")
                        .HasColumnType("int");

                    b.Property<int>("StaffID")
                        .HasColumnType("int");

                    b.HasKey("DeletionRequestID");

                    b.ToTable("DeletionRequest", "Production");

                    b.HasData(
                        new
                        {
                            DeletionRequestID = 1,
                            CustomerID = 1,
                            DateApproved = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateRequested = new DateTime(2010, 10, 1, 8, 5, 3, 0, DateTimeKind.Unspecified),
                            DeletionReason = "Staging Terrible Site.",
                            DeletionRequestStatus = 1,
                            StaffID = 1
                        },
                        new
                        {
                            DeletionRequestID = 2,
                            CustomerID = 2,
                            DateApproved = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateRequested = new DateTime(2012, 1, 2, 10, 3, 45, 0, DateTimeKind.Unspecified),
                            DeletionReason = "Staging Prefer Amazon.",
                            DeletionRequestStatus = 1,
                            StaffID = 1
                        },
                        new
                        {
                            DeletionRequestID = 3,
                            CustomerID = 3,
                            DateApproved = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateRequested = new DateTime(2013, 2, 3, 12, 2, 40, 0, DateTimeKind.Unspecified),
                            DeletionReason = "Staging Too many clicks.",
                            DeletionRequestStatus = 1,
                            StaffID = 2
                        },
                        new
                        {
                            DeletionRequestID = 4,
                            CustomerID = 4,
                            DateApproved = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateRequested = new DateTime(2014, 3, 4, 14, 1, 35, 0, DateTimeKind.Unspecified),
                            DeletionReason = "Staging Scammed into signing up.",
                            DeletionRequestStatus = 1,
                            StaffID = 3
                        },
                        new
                        {
                            DeletionRequestID = 5,
                            CustomerID = 5,
                            DateApproved = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateRequested = new DateTime(2007, 4, 5, 16, 50, 30, 0, DateTimeKind.Unspecified),
                            DeletionReason = "Staging If Wish was built by students...",
                            DeletionRequestStatus = 1,
                            StaffID = 4
                        },
                        new
                        {
                            DeletionRequestID = 6,
                            CustomerID = 1,
                            DateApproved = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateRequested = new DateTime(2010, 10, 1, 8, 5, 3, 0, DateTimeKind.Unspecified),
                            DeletionReason = "Production Terrible Site.",
                            DeletionRequestStatus = 1,
                            StaffID = 1
                        },
                        new
                        {
                            DeletionRequestID = 7,
                            CustomerID = 2,
                            DateApproved = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateRequested = new DateTime(2012, 1, 2, 10, 3, 45, 0, DateTimeKind.Unspecified),
                            DeletionReason = "Production Prefer Amazon.",
                            DeletionRequestStatus = 1,
                            StaffID = 1
                        },
                        new
                        {
                            DeletionRequestID = 8,
                            CustomerID = 3,
                            DateApproved = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateRequested = new DateTime(2013, 2, 3, 12, 2, 40, 0, DateTimeKind.Unspecified),
                            DeletionReason = "Production Too many clicks.",
                            DeletionRequestStatus = 1,
                            StaffID = 2
                        },
                        new
                        {
                            DeletionRequestID = 9,
                            CustomerID = 4,
                            DateApproved = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateRequested = new DateTime(2014, 3, 4, 14, 1, 35, 0, DateTimeKind.Unspecified),
                            DeletionReason = "Production Scammed into signing up.",
                            DeletionRequestStatus = 1,
                            StaffID = 3
                        },
                        new
                        {
                            DeletionRequestID = 10,
                            CustomerID = 5,
                            DateApproved = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateRequested = new DateTime(2007, 4, 5, 16, 50, 30, 0, DateTimeKind.Unspecified),
                            DeletionReason = "Production If Wish was built by students...",
                            DeletionRequestStatus = 1,
                            StaffID = 4
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
